In [1]:
import yfinance as yf
import warnings
warnings.filterwarnings("ignore",category=UserWarning)

In [2]:
stock=['RELIANCE.NS','INFY.NS','HDFCBANK.NS','BHARTIARTL.NS','ASIANPAINT.NS']
IS=yf.download(stock,period='1y',interval='1d')
IS=IS.stack(level=1,future_stack=True).reset_index()
IS

[**********************80%*************          ]  4 of 5 completed

Price,Date,Ticker,Close,High,Low,Open,Volume
0,2025-10-09,ASIANPAINT.NS,2312.694336,2317.247760,2300.222323,2304.874588,587567
1,2025-10-09,BHARTIARTL.NS,1917.863281,1924.578814,1907.296318,1920.825995,3945737
2,2025-10-09,HDFCBANK.NS,961.202209,963.071320,954.365336,958.644536,15370950
3,2025-10-09,INFY.NS,1455.056274,1459.587311,1433.557682,1448.018587,7028753
4,2025-10-09,RELIANCE.NS,1371.458984,1373.648811,1362.798952,1367.676425,8826633
...,...,...,...,...,...,...,...
1235,2026-10-09,ASIANPAINT.NS,2337.899902,2342.399902,2322.199951,2324.000000,23635
1236,2026-10-09,BHARTIARTL.NS,1807.699951,1812.500000,1801.400024,1804.599976,477829
1237,2026-10-09,HDFCBANK.NS,702.000000,702.250000,695.299988,696.599976,2384516
1238,2026-10-09,INFY.NS,1018.849976,1026.699951,1007.299988,1007.299988,2711076
1239,2026-10-09,RELIANCE.NS,1164.599976,1179.000000,1161.000000,1179.000000,2701649

In [3]:
IS.rename(columns={'Datetime':'Date_time','Ticker':'Company','Close':'Closeing_time_price','Open':'Opening_time_price','Volume':'Total_stocks_sold'
                  ,'High':'High_price','Low':'Low_price'},inplace=True)

In [4]:
IS.shape

(1240, 7)

In [5]:
IS.columns

Index(['Date', 'Company', 'Closeing_time_price', 'High_price', 'Low_price',
       'Opening_time_price', 'Total_stocks_sold'],
      dtype='object', name='Price')

In [6]:
IS.dtypes

Price
Date                   datetime64[ns]
Company                        object
Closeing_time_price           float64
High_price                    float64
Low_price                     float64
Opening_time_price            float64
Total_stocks_sold               int64
dtype: object

In [7]:
IS.isnull().sum()

Price
Date                   0
Company                0
Closeing_time_price    0
High_price             0
Low_price              0
Opening_time_price     0
Total_stocks_sold      0
dtype: int64

In [8]:
IS=IS.dropna()

In [9]:
IS=IS.reset_index(drop=True)
IS

Price,Date,Company,Closeing_time_price,High_price,Low_price,Opening_time_price,Total_stocks_sold
0,2025-10-09,ASIANPAINT.NS,2312.694336,2317.247760,2300.222323,2304.874588,587567
1,2025-10-09,BHARTIARTL.NS,1917.863281,1924.578814,1907.296318,1920.825995,3945737
2,2025-10-09,HDFCBANK.NS,961.202209,963.071320,954.365336,958.644536,15370950
3,2025-10-09,INFY.NS,1455.056274,1459.587311,1433.557682,1448.018587,7028753
4,2025-10-09,RELIANCE.NS,1371.458984,1373.648811,1362.798952,1367.676425,8826633
...,...,...,...,...,...,...,...
1235,2026-10-09,ASIANPAINT.NS,2337.899902,2342.399902,2322.199951,2324.000000,23635
1236,2026-10-09,BHARTIARTL.NS,1807.699951,1812.500000,1801.400024,1804.599976,477829
1237,2026-10-09,HDFCBANK.NS,702.000000,702.250000,695.299988,696.599976,2384516
1238,2026-10-09,INFY.NS,1018.849976,1026.699951,1007.299988,1007.299988,2711076
1239,2026-10-09,RELIANCE.NS,1164.599976,1179.000000,1161.000000,1179.000000,2701649

In [10]:
IS.describe()

Price,Date,Closeing_time_price,High_price,Low_price,Opening_time_price,Total_stocks_sold
count,1240,1240.000000,1240.000000,1240.000000,1240.000000,1.240000e+03
mean,2026-04-10 11:30:58.064516096,1596.326807,1612.140443,1581.722125,1596.878482,1.326348e+07
min,2025-10-09 00:00:00,687.099976,694.500000,681.900024,683.900024,0.000000e+00
25%,2026-01-07 18:00:00,1125.875000,1141.325012,1116.950012,1129.274963,4.298518e+06
50%,2026-04-11 12:00:00,1462.050171,1476.164958,1451.537005,1464.271575,8.938845e+06
75%,2026-07-13 06:00:00,1996.844299,2015.509301,1979.512364,1997.979931,1.761075e+07
max,2026-10-09 00:00:00,2942.966797,2960.018776,2915.703335,2944.453822,1.716374e+08
std,NaN,612.795041,618.730497,606.755375,612.590618,1.431574e+07

In [11]:
import mysql.connector as mc
import pandas as pd

In [12]:
#created conneaction between Jupyter notebook and MYSQl
DB=mc.connect(
    host='localhost',
    port=3306,
    user='root',
    password='423155',
    database='indian_stocks')
cursor = DB.cursor(buffered=True)

In [13]:
query= """ 
INSERT INTO indian_stocks(Date_time,Company,Closeing_time_price,High_price,Low_price,Opening_time_price,Total_stocks_sold)
VALUES(%s,%s,%s,%s,%s,%s,%s) """

In [14]:
cursor.execute('TRUNCATE TABLE indian_stocks')
for row in IS.itertuples(index=False,name=None):
    cursor.execute(query ,row)
DB.commit()
print("Data inserted successfully")

Data inserted successfully

In [15]:
Relaince="select Date_time, Company,Closeing_time_price, High_price,Low_price,Opening_time_price,Total_stocks_sold from indian_stocks WHERE company='RELIANCE.NS'"
Relaince=pd.read_sql(Relaince, DB)
Reliance=Relaince
Reliance

,Date_time,Company,Closeing_time_price,High_price,Low_price,Opening_time_price,Total_stocks_sold
0,2025-10-09,RELIANCE.NS,1371.458984,1373.648811,1362.798952,1367.676425,8826633
1,2025-10-10,RELIANCE.NS,1375.340942,1381.611996,1368.771342,1371.458989,6373084
2,2025-10-13,RELIANCE.NS,1368.671875,1371.359400,1361.505060,1370.563155,7600682
3,2025-10-14,RELIANCE.NS,1369.567749,1381.612037,1363.794394,1373.648855,9768174
4,2025-10-15,RELIANCE.NS,1367.975098,1377.630407,1366.382364,1376.635009,10882743
...,...,...,...,...,...,...,...
243,2026-10-05,RELIANCE.NS,1186.400024,1193.000000,1171.199951,1171.199951,14254907
244,2026-10-06,RELIANCE.NS,1218.000000,1219.099976,1188.099976,1188.099976,18003127
245,2026-10-07,RELIANCE.NS,1207.699951,1220.800049,1203.500000,1212.000000,11880731
246,2026-10-08,RELIANCE.NS,1178.000000,1208.000000,1173.000000,1207.699951,13965493
247,2026-10-09,RELIANCE.NS,1164.599976,1179.000000,1161.000000,1179.000000,2701649

In [16]:
Asianpaint="select Date_time , Company,Closeing_time_price, High_price,Low_price,Opening_time_price,Total_stocks_sold from indian_stocks WHERE company='ASIANPAINT.NS'"
Asianpaint=pd.read_sql(Asianpaint, DB)
Asianpaint

,Date_time,Company,Closeing_time_price,High_price,Low_price,Opening_time_price,Total_stocks_sold
0,2025-10-09,ASIANPAINT.NS,2312.694336,2317.247760,2300.222323,2304.874588,587567
1,2025-10-10,ASIANPAINT.NS,2316.455811,2333.877334,2312.892482,2315.168952,1117236
2,2025-10-13,ASIANPAINT.NS,2318.732666,2342.588241,2313.288470,2316.455954,667732
3,2025-10-14,ASIANPAINT.NS,2294.580322,2331.105833,2284.582702,2318.633578,353345
4,2025-10-15,ASIANPAINT.NS,2351.001953,2359.811556,2301.410179,2306.359448,753640
...,...,...,...,...,...,...,...
243,2026-10-05,ASIANPAINT.NS,2366.000000,2409.000000,2336.699951,2400.000000,916254
244,2026-10-06,ASIANPAINT.NS,2424.199951,2424.199951,2349.000000,2369.100098,439473
245,2026-10-07,ASIANPAINT.NS,2372.100098,2403.199951,2360.199951,2371.800049,522763
246,2026-10-08,ASIANPAINT.NS,2311.600098,2367.000000,2311.600098,2364.399902,652405
247,2026-10-09,ASIANPAINT.NS,2337.899902,2342.399902,2322.199951,2324.000000,23635

In [17]:
Bhartiartl="select Date_time , Company,Closeing_time_price, High_price,Low_price,Opening_time_price,Total_stocks_sold from indian_stocks WHERE company='BHARTIARTL.NS'"
Bhartiartl=pd.read_sql(Bhartiartl, DB)
Bhartiartl

,Date_time,Company,Closeing_time_price,High_price,Low_price,Opening_time_price,Total_stocks_sold
0,2025-10-09,BHARTIARTL.NS,1917.863281,1924.578814,1907.296318,1920.825995,3945737
1,2025-10-10,BHARTIARTL.NS,1915.789307,1923.393556,1911.345236,1912.925326,2512581
2,2025-10-13,BHARTIARTL.NS,1930.602905,1941.466188,1911.937786,1913.814195,3672419
3,2025-10-14,BHARTIARTL.NS,1922.406006,1939.589768,1915.097955,1939.589768,4454239
4,2025-10-15,BHARTIARTL.NS,1944.033813,1951.440597,1927.343837,1932.874211,3447352
...,...,...,...,...,...,...,...
243,2026-10-05,BHARTIARTL.NS,1779.900024,1779.900024,1742.300049,1742.300049,7310041
244,2026-10-06,BHARTIARTL.NS,1810.500000,1810.500000,1771.400024,1777.000000,5155150
245,2026-10-07,BHARTIARTL.NS,1833.900024,1854.699951,1810.500000,1823.000000,13920833
246,2026-10-08,BHARTIARTL.NS,1804.599976,1847.800049,1789.699951,1847.800049,6582419
247,2026-10-09,BHARTIARTL.NS,1807.699951,1812.500000,1801.400024,1804.599976,477829

In [18]:
Hdfc="select Date_time , Company,Closeing_time_price, High_price,Low_price,Opening_time_price,Total_stocks_sold from indian_stocks WHERE company='HDFCBANK.NS'"
Hdfc=pd.read_sql(Hdfc, DB)
Hdfc

,Date_time,Company,Closeing_time_price,High_price,Low_price,Opening_time_price,Total_stocks_sold
0,2025-10-09,HDFCBANK.NS,961.202209,963.071320,954.365336,958.644536,15370950
1,2025-10-10,HDFCBANK.NS,964.940430,970.154185,962.185939,963.071319,13757080
2,2025-10-13,HDFCBANK.NS,961.103882,965.038800,956.185234,958.447800,18634254
3,2025-10-14,HDFCBANK.NS,961.251465,964.497761,951.266585,954.217774,22934382
4,2025-10-15,HDFCBANK.NS,962.333557,968.875384,957.513258,959.136436,23310447
...,...,...,...,...,...,...,...
243,2026-10-05,HDFCBANK.NS,704.799988,734.200012,701.250000,731.950012,66056690
244,2026-10-06,HDFCBANK.NS,711.450012,714.700012,701.000000,705.599976,26568270
245,2026-10-07,HDFCBANK.NS,702.750000,711.000000,701.700012,708.549988,29944008
246,2026-10-08,HDFCBANK.NS,692.250000,705.799988,690.500000,704.049988,26808765
247,2026-10-09,HDFCBANK.NS,702.000000,702.250000,695.299988,696.599976,2384516

In [19]:
Infy="select Date_time , Company,Closeing_time_price, High_price,Low_price,Opening_time_price,Total_stocks_sold from indian_stocks where company = 'INFY.NS'"
Infy=pd.read_sql(Infy , DB)
Infy

,Date_time,Company,Closeing_time_price,High_price,Low_price,Opening_time_price,Total_stocks_sold
0,2025-10-09,INFY.NS,1455.056274,1459.587311,1433.557682,1448.018587,7028753
1,2025-10-10,INFY.NS,1460.454956,1467.010495,1444.933609,1455.731037,3738353
2,2025-10-13,INFY.NS,1439.534790,1450.621483,1430.087070,1443.198266,5859355
3,2025-10-14,INFY.NS,1436.353516,1459.972994,1433.075687,1445.126441,5600789
4,2025-10-15,INFY.NS,1421.410645,1435.100255,1414.758604,1430.569218,6986098
...,...,...,...,...,...,...,...
243,2026-10-05,INFY.NS,1020.500000,1052.300049,1010.000000,1050.000000,12126808
244,2026-10-06,INFY.NS,1013.849976,1020.500000,1003.150024,1018.000000,8252213
245,2026-10-07,INFY.NS,992.000000,1009.000000,990.099976,1006.000000,7493993
246,2026-10-08,INFY.NS,997.000000,1012.650024,992.900024,1002.000000,14847874
247,2026-10-09,INFY.NS,1018.849976,1026.699951,1007.299988,1007.299988,2711076

In [20]:
#creating target column for every comapny
Asianpaint['Target_Price'] =  Asianpaint['Closeing_time_price'].shift(-1)
Infy['Target_Price']=Infy['Closeing_time_price'].shift(-1)
Reliance['Target_Price']=Reliance['Closeing_time_price'].shift(-1)
Hdfc['Target_Price']=Hdfc['Closeing_time_price'].shift(-1)
Bhartiartl['Target_Price']=Bhartiartl['Closeing_time_price'].shift(-1)

In [21]:
Asianpaint

,Date_time,Company,Closeing_time_price,High_price,Low_price,Opening_time_price,Total_stocks_sold,Target_Price
0,2025-10-09,ASIANPAINT.NS,2312.694336,2317.247760,2300.222323,2304.874588,587567,2316.455811
1,2025-10-10,ASIANPAINT.NS,2316.455811,2333.877334,2312.892482,2315.168952,1117236,2318.732666
2,2025-10-13,ASIANPAINT.NS,2318.732666,2342.588241,2313.288470,2316.455954,667732,2294.580322
3,2025-10-14,ASIANPAINT.NS,2294.580322,2331.105833,2284.582702,2318.633578,353345,2351.001953
4,2025-10-15,ASIANPAINT.NS,2351.001953,2359.811556,2301.410179,2306.359448,753640,2385.250732
...,...,...,...,...,...,...,...,...
243,2026-10-05,ASIANPAINT.NS,2366.000000,2409.000000,2336.699951,2400.000000,916254,2424.199951
244,2026-10-06,ASIANPAINT.NS,2424.199951,2424.199951,2349.000000,2369.100098,439473,2372.100098
245,2026-10-07,ASIANPAINT.NS,2372.100098,2403.199951,2360.199951,2371.800049,522763,2311.600098
246,2026-10-08,ASIANPAINT.NS,2311.600098,2367.000000,2311.600098,2364.399902,652405,2337.899902
247,2026-10-09,ASIANPAINT.NS,2337.899902,2342.399902,2322.199951,2324.000000,23635,NaN

In [22]:
Asianpaint=Asianpaint.dropna()
Bhartiartl=Bhartiartl.dropna()
Hdfc=Hdfc.dropna()
Infy=Infy.dropna()
Reliance=Reliance.dropna()

In [23]:
#Training the Asianpaint Model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error,root_mean_squared_error
import joblib as jl

In [24]:
#Training the Asianpaint Mode
AX=Asianpaint[['Closeing_time_price','High_price','Low_price','Opening_time_price','Total_stocks_sold']] #input features
AY=Asianpaint['Target_Price'] #target features
X_Asianpaint_train,X_Asianpaint_test,Y_Asianpaint_train,Y_Asianpaint_test=train_test_split(AX,AY,test_size=0.2,random_state=42)
AL=LinearRegression() #Model creation
AL.fit(X_Asianpaint_train,Y_Asianpaint_train) #model train
Y_Asianpaint_test_pred=AL.predict(X_Asianpaint_test) #predicting the test data
print('R2score:',r2_score(Y_Asianpaint_test,Y_Asianpaint_test_pred))
print('MAE:',mean_absolute_error(Y_Asianpaint_test,Y_Asianpaint_test_pred))
Asianpaint['Predicted_Value']=AL.predict(AX)
jl.dump(AL , 'Asianpaint.pkl')

R2score: 0.9642102638892605
MAE: 29.70768220369574

C:\Users\madhu\AppData\Local\Temp\ipykernel_23140\2454272855.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Asianpaint['Predicted_Value']=AL.predict(AX)

['Asianpaint.pkl']

In [25]:
#Training the Bharatiartl Model
BX=Bhartiartl[['Closeing_time_price','High_price','Low_price','Opening_time_price','Total_stocks_sold']]  #input features
BY=Bhartiartl['Target_Price'] #target features
X_Bhartiartl_train,X_Bhartiartl_test,Y_Bhartiartl_train,Y_Bhartiartl_test=train_test_split(BX,BY,test_size=0.2,random_state=42)
BL=LinearRegression() #Model creation
BL.fit(X_Bhartiartl_train,Y_Bhartiartl_train) #model train
Y_Bhartiartl_test_pred=BL.predict(X_Bhartiartl_test) #predicting the test data
print('R2score:',r2_score(Y_Bhartiartl_test,Y_Bhartiartl_test_pred))
print('MAE:',mean_absolute_error(Y_Bhartiartl_test,Y_Bhartiartl_test_pred))
Bhartiartl['Predicted_Value']=BL.predict(BX) 
jl.dump(BL , 'Bhartiartl.pkl')

R2score: 0.9315837398872086
MAE: 22.26142652275515

C:\Users\madhu\AppData\Local\Temp\ipykernel_23140\1527660239.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Bhartiartl['Predicted_Value']=BL.predict(BX)

['Bhartiartl.pkl']

In [26]:
#Training the Hdfc model
HX=Hdfc[['Closeing_time_price','High_price','Low_price','Opening_time_price','Total_stocks_sold']] #input featured
HY=Hdfc['Target_Price']                                      #Target value
X_Hdfc_train,X_Hdfc_test,Y_Hdfc_train,Y_Hdfc_test=train_test_split(HX,HY,test_size=0.2,random_state=42) 
HL=LinearRegression() #model creation
HL.fit(X_Hdfc_train,Y_Hdfc_train)    #model training
Y_Hdfc_test_pred = HL.predict(X_Hdfc_test) #predicting the test data
print('R2score:',r2_score(Y_Hdfc_test,Y_Hdfc_test_pred))
print('MAE:',mean_absolute_error(Y_Hdfc_test,Y_Hdfc_test_pred))
Hdfc['Predicted_Value']=HL.predict(HX)
Hdfc
jl.dump(HL , 'Hdfc.pkl')

R2score: 0.987938604849939
MAE: 7.709860802484347

C:\Users\madhu\AppData\Local\Temp\ipykernel_23140\3642218529.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Hdfc['Predicted_Value']=HL.predict(HX)

['Hdfc.pkl']

In [27]:
IX=Infy[['Closeing_time_price','High_price','Low_price','Opening_time_price','Total_stocks_sold']]  #input features
IY=Infy['Target_Price']                                       #Target value
X_Infy_train,X_Infy_test,Y_Infy_train,Y_Infy_test=train_test_split(IX,IY,test_size=0.2,random_state=42)
IL=LinearRegression()                                     #model creation
IL.fit(X_Infy_train,Y_Infy_train)               #model training
Y_Infy_test_pred=IL.predict(X_Infy_test)
print('R2score:',r2_score(Y_Infy_test,Y_Infy_test_pred))
print('MAE:',mean_absolute_error(Y_Infy_test,Y_Infy_test_pred))
Infy['Predicted_Value']=IL.predict(IX)
Infy
jl.dump(IL , 'Infy.pkl')

R2score: 0.9837803325691779
MAE: 19.852857113136135

C:\Users\madhu\AppData\Local\Temp\ipykernel_23140\1428720135.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Infy['Predicted_Value']=IL.predict(IX)

['Infy.pkl']

In [28]:
RX=Reliance[['Closeing_time_price','High_price','Low_price','Opening_time_price','Total_stocks_sold']]
RY=Reliance['Target_Price']
X_Reliance_train,X_Reliance_test,Y_Reliance_train,Y_Reliance_test=train_test_split(RX,RY,test_size=0.2,random_state=42)
RL=LinearRegression()
RL.fit(X_Reliance_train,Y_Reliance_train)
Y_Reliance_test_pred=RL.predict(X_Reliance_test)
print('R2score:',r2_score(Y_Reliance_test,Y_Reliance_test_pred))
print('MAE:',mean_absolute_error(Y_Reliance_test,Y_Reliance_test_pred))
Reliance['Predicted_Value']=RL.predict(RX)
jl.dump(RL , 'Reliance.pkl')

R2score: 0.9682250730015995
MAE: 14.056010526823638

C:\Users\madhu\AppData\Local\Temp\ipykernel_23140\1940027132.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Reliance['Predicted_Value']=RL.predict(RX)

['Reliance.pkl']

In [29]:
Amodel = jl.load('Asianpaint.pkl') # import model for prepartion
Asianpaint=pd.read_sql("select * from indian_stocks where Company = 'ASIANPAINT.NS' order by Date_time desc limit 1" , DB) # importlast row
AX_latest=Asianpaint[['Closeing_time_price','High_price','Low_price','Opening_time_price','Total_stocks_sold']]
Predicted_Value=Amodel.predict(AX_latest)
Predicted_Value

#adding predicted value to mysql table 
Predicted_Value=float(Predicted_Value[0])
cursor.execute("""update indian_stocks set Predicted_Value = %s WHERE Company = %s order by Date_time DESC limit 1 """,(Predicted_Value,"ASIANPAINT.NS"))
DB.commit()
print("updated successfully")

updated successfully

In [30]:
Bmodel = jl.load('Bhartiartl.pkl')
Bhartiartl=pd.read_sql("select * from indian_stocks where Company = 'BHARTIARTL.NS' order by Date_time desc limit 1",DB)
BX_latest=Bhartiartl[['Closeing_time_price','High_price','Low_price','Opening_time_price','Total_stocks_sold']]
Predicted_Value=Bmodel.predict(BX_latest)
Predicted_Value

#import predicted value into Mysql tabel
Predicted_Value=float(Predicted_Value)
cursor.execute(""" update indian_stocks set Predicted_Value = %s where Company = %s order by Date_time desc limit 1 """,(Predicted_Value,"BHARTIARTL.NS"))
DB.commit()

C:\Users\madhu\AppData\Local\Temp\ipykernel_23140\1743233272.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  Predicted_Value=float(Predicted_Value)

In [31]:
Hmodel = jl.load('Hdfc.pkl')
Hdfc=pd.read_sql("select * from indian_stocks where Company = 'HDFCBANK.NS' order by Date_time desc limit 1",DB)
HX_latest=Hdfc[['Closeing_time_price','High_price','Low_price','Opening_time_price','Total_stocks_sold']]
Predicted_Value=Hmodel.predict(HX_latest)
Predicted_Value

#import predicted value into Mysql tabel
Predicted_Value=float(Predicted_Value)
cursor.execute(""" update indian_stocks set Predicted_Value = %s where Company = %s order by Date_time desc limit 1 """,(Predicted_Value,"HDFCBANK.NS"))
DB.commit()

C:\Users\madhu\AppData\Local\Temp\ipykernel_23140\2322153806.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  Predicted_Value=float(Predicted_Value)

In [32]:
Imodel = jl.load('Infy.pkl')
Infy=pd.read_sql("select * from indian_stocks where Company = 'INFY.NS' order by Date_time desc limit 1",DB)
IX_latest=Infy[['Closeing_time_price','High_price','Low_price','Opening_time_price','Total_stocks_sold']]
Predicted_Value=Imodel.predict(IX_latest)
Predicted_Value

#import predicted value into Mysql tabel
Predicted_Value=float(Predicted_Value)
cursor.execute(""" update indian_stocks set Predicted_Value = %s where Company = %s order by Date_time desc limit 1 """,(Predicted_Value,"INFY.NS"))
DB.commit()

C:\Users\madhu\AppData\Local\Temp\ipykernel_23140\2878235921.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  Predicted_Value=float(Predicted_Value)

In [33]:
Rmodel = jl.load('Reliance.pkl')
Reliance=pd.read_sql("select * from indian_stocks where Company = 'RELIANCE.NS' order by Date_time desc limit 1",DB)
RX_latest=Reliance[['Closeing_time_price','High_price','Low_price','Opening_time_price','Total_stocks_sold']]
Predicted_Value=Rmodel.predict(RX_latest)
Predicted_Value

#import predicted value into Mysql tabel
Predicted_Value=float(Predicted_Value)
cursor.execute(""" update indian_stocks set Predicted_Value = %s where Company = %s order by Date_time desc limit 1 """,(Predicted_Value,"RELIANCE.NS"))
DB.commit()

C:\Users\madhu\AppData\Local\Temp\ipykernel_23140\1708949136.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  Predicted_Value=float(Predicted_Value)